In [ ]:
car.head(4)

                     name   company  year   Price  kms_driven fuel_type
0     Hyundai Santro Xing   Hyundai  2007   80000       45000    Petrol
1     Mahindra Jeep CL550  Mahindra  2006  425000          40    Diesel
2       Hyundai Grand i10   Hyundai  2014  325000       28000    Petrol
3  Ford EcoSport Titanium      Ford  2014  575000       36000    Diesel

## Import & Loading

In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [2]:
car = pd.read_csv('raw_data.csv')

FileNotFoundError: [Errno 2] No such file or directory: 'raw_data.csv'

In [ ]:
car.head()

,name,company,year,Price,kms_driven,fuel_type
0,Hyundai Santro Xing XO eRLX Euro III,Hyundai,2007,"80,000","45,000 kms",Petrol
1,Mahindra Jeep CL550 MDI,Mahindra,2006,"4,25,000",40 kms,Diesel
2,Maruti Suzuki Alto 800 Vxi,Maruti,2018,Ask For Price,"22,000 kms",Petrol
3,Hyundai Grand i10 Magna 1.2 Kappa VTVT,Hyundai,2014,"3,25,000","28,000 kms",Petrol
4,Ford EcoSport Titanium 1.5L TDCi,Ford,2014,"5,75,000","36,000 kms",Diesel

In [ ]:
car.shape

(892, 6)

In [ ]:
car.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 892 entries, 0 to 891
Data columns (total 6 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   name        892 non-null    object
 1   company     892 non-null    object
 2   year        892 non-null    object
 3   Price       892 non-null    object
 4   kms_driven  840 non-null    object
 5   fuel_type   837 non-null    object
dtypes: object(6)
memory usage: 41.9+ KB

## Data Cleaning

In [ ]:
car2 = car.copy()

In [ ]:
car['year'].unique()

array(['2007', '2006', '2018', '2014', '2015', '2012', '2013', '2016',
       '2010', '2017', '2008', '2011', '2019', '2009', '2005', '2000',
       '...', '150k', 'TOUR', '2003', 'r 15', '2004', 'Zest', '/-Rs',
       'sale', '1995', 'ara)', '2002', 'SELL', '2001', 'tion', 'odel',
       '2 bs', 'arry', 'Eon', 'o...', 'ture', 'emi', 'car', 'able', 'no.',
       'd...', 'SALE', 'digo', 'sell', 'd Ex', 'n...', 'e...', 'D...',
       ', Ac', 'go .', 'k...', 'o c4', 'zire', 'cent', 'Sumo', 'cab',
       't xe', 'EV2', 'r...', 'zest'], dtype=object)

In [ ]:
car = car[car['year'].str.isnumeric()]

In [ ]:
car['year'] = car['year'].astype(int)

In [ ]:
car['year'].unique()

array([2007, 2006, 2018, 2014, 2015, 2012, 2013, 2016, 2010, 2017, 2008,
       2011, 2019, 2009, 2005, 2000, 2003, 2004, 1995, 2002, 2001])

In [ ]:
#car['Price'].unique()

In [ ]:
car = car[car['Price'] != 'Ask For Price']

In [ ]:
car['Price'] = car['Price'].str.replace(',','').astype(int)
#Convert comma(,) with empty string('')

In [ ]:
car['Price'].unique()

array([  80000,  425000,  325000,  575000,  175000,  190000,  830000,
        250000,  182000,  315000,  415000,  320000, 1000000,  500000,
        350000,  160000,  310000,   75000,  100000,  290000,   95000,
        180000,  385000,  105000,  650000,  689999,  448000,  549000,
        501000,  489999,  280000,  349999,  284999,  345000,  499999,
        235000,  249999, 1475000,  395000,  220000,  170000,   85000,
        200000,  570000,  110000,  448999, 1891111,  159500,  344999,
        449999,  865000,  699000,  375000,  224999, 1200000,  195000,
        351000,  240000,   90000,  155000,  600000,  189500,  210000,
        390000,  135000, 1600000,  701000,  265000,  525000,  372000,
        635000,  550000,  485000,  329500,  251111,  569999,   69999,
        299999,  399999,  450000,  270000,  158400,  179000,  125000,
        299000,  150000,  275000,  285000,  340000,   70000,  289999,
        849999,  749999,  274999,  984999,  599999,  244999,  474999,
        245000,  169500,  370000,  168000,  145000,   98500,  209000,
        185000,  900000,  699999,  199999,  544999,  199000,  540000,
         49000,  700000,   55000,  895000,  355000,  565000,  365000,
         40000,  400000,  330000,  580000,  379000,  219000,  519000,
        730000, 2000000, 2100000, 1400000,  311000,  855000,  535000,
        178000,  300000,  255000,  549999,  380000,   57000,  410000,
        225000,  120000,   59000,  599000,  675000,   72500,  610000,
        230000,  520000,  524999,  424999,  644999,  584999,  799999,
        444999,  649999,  944999,  574999,  374999,  130000,  401000,
       1350000,  174999,  239999,   99999,  324999, 1074999, 1130000,
        149000,  770000,   30000,  335000,  399000,   65000,  169999,
        165000,  560000,  950000,  715000,   45000,  940000,  155555,
       1500000,  495000,  800000, 1299000,  530000, 1499000,   32000,
        405000,  760000,  750000,  419000,  140000, 1540000,  123000,
        498000,  480000,  488000, 1525000,  548900,  725000,   99000,
         52000, 2800000,  499000,  381000,  278000,  690000,  260000,
         90001,  115000, 1599000,  159000,   51999,  215000,   35000,
       1150000,  269000,   60000,  430000, 8500003,  401919,  490000,
        424000,  205000,  549900,  435000,  189700,  389700,  360000,
        295000,  114990, 1065000,  470000,   48000,  188000,  465000,
        179999, 2190000, 2390000, 1075000,  475000, 1025000,  615000,
       1900000, 1490000, 1510000, 1850000,  790000, 1725000, 1225000,
         68000,  970000, 3100000,  899000,   88000,   53000,  568500,
         71000,  590000,  795000,   42000,  189000,  162000,   35999,
       2900000,   39999,   50500,  510000,  860000,  500001])

In [ ]:
#car['kms_driven'].unique()

In [ ]:
car['kms_driven'] = car['kms_driven'].str.split(' ').str.get(0).str.replace(',','')

In [ ]:
car = car[car['kms_driven'].str.isnumeric()]

In [ ]:
car['kms_driven'] = car['kms_driven'].astype(int)

In [ ]:
car = car[~car['fuel_type'].isna()]

In [ ]:
car['name'] = car['name'].str.split(' ').str.slice(0,3).str.join(' ')

In [ ]:
car = car.reset_index(drop=True)

In [ ]:
car.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 816 entries, 0 to 815
Data columns (total 6 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   name        816 non-null    object
 1   company     816 non-null    object
 2   year        816 non-null    int64
 3   Price       816 non-null    int64
 4   kms_driven  816 non-null    int64
 5   fuel_type   816 non-null    object
dtypes: int64(3), object(3)
memory usage: 38.4+ KB

In [ ]:
car.describe()

              year         Price     kms_driven
count   816.000000  8.160000e+02     816.000000
mean   2012.444853  4.117176e+05   46275.531863
std       4.002992  4.751844e+05   34297.428044
min    1995.000000  3.000000e+04       0.000000
25%    2010.000000  1.750000e+05   27000.000000
50%    2013.000000  2.999990e+05   41000.000000
75%    2015.000000  4.912500e+05   56818.500000
max    2019.000000  8.500003e+06  400000.000000

In [ ]:
car[car['Price']>6e6]           # Car above 60lakh

                   name   company  year    Price  kms_driven fuel_type
534  Mahindra XUV500 W6  Mahindra  2014  8500003       45000    Diesel

In [ ]:
car = car[car['Price']<6e6]            #Keep car below 60lakh ,removing outliers

In [ ]:
car = car.reset_index(drop=True)

In [ ]:
car.shape

(815, 6)

In [ ]:
car.to_csv('Cleaned_Car_data.csv')          #Saving our processed cleaned data to csv format

## Model

In [ ]:
x = car.drop(columns='Price')
y = car['Price']

In [ ]:
#x
#y

In [ ]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test = train_test_split(x,y,test_size=0.2)

In [ ]:
from sklearn.linear_model import LinearRegression
from sklearn.metrics import r2_score
from sklearn.preprocessing import OneHotEncoder
from sklearn.compose import make_column_transformer
from sklearn.pipeline import make_pipeline
#

In [ ]:
ohe = OneHotEncoder()
ohe.fit(x[['name','company','fuel_type']])

OneHotEncoder()

In [ ]:
column_trans = make_column_transformer((OneHotEncoder(categories=ohe.categories_),['name','company','fuel_type']),
                                      remainder='passthrough')

In [ ]:
 #                  OR

In [ ]:
column_trans = make_column_transformer(
    (OneHotEncoder(handle_unknown='ignore'), ['name','company','fuel_type']),
    remainder='passthrough')

In [ ]:
lr = LinearRegression()

In [ ]:
pipe = make_pipeline(column_trans,lr)

In [ ]:
pipe.fit(x_train,y_train)

/usr/local/lib/python3.12/dist-packages/sklearn/compose/_column_transformer.py:1667: FutureWarning:
The format of the columns of the 'remainder' transformer in ColumnTransformer.transformers_ will change in version 1.7 to match the format of the other transformers.
At the moment the remainder columns are stored as indices (of type int). With the same ColumnTransformer configuration, in the future they will be stored as column names (of type str).
To use the new behavior now and suppress this warning, use ColumnTransformer(force_int_remainder_cols=False).

  warnings.warn(

Pipeline(steps=[('columntransformer',
                 ColumnTransformer(remainder='passthrough',
                                   transformers=[('onehotencoder',
                                                  OneHotEncoder(handle_unknown='ignore'),
                                                  ['name', 'company',
                                                   'fuel_type'])])),
                ('linearregression', LinearRegression())])

In [ ]:
y_preds = pipe.predict(x_test)

In [ ]:
r2_score(y_test,y_preds)

0.8457059008496111

In [ ]:
scores = []
for i in range(1000):
    x_train,x_test,y_train,y_test = train_test_split(x,y,test_size=0.2,random_state=i)
    lr = LinearRegression()
    pipe = make_pipeline(column_trans,lr)
    pipe.fit(x_train,y_train)
    y_preds = pipe.predict(x_test)
    scores.append(r2_score(y_test,y_preds))

In [ ]:
np.argmax(scores)           # random_state value with maximum r2 score

np.int64(433)

In [ ]:
scores[np.argmax(scores)]       # r2 score

0.8457059008496111

In [ ]:
x_train,x_test,y_train,y_test = train_test_split(x,y,test_size=0.2,random_state=np.argmax(scores))
lr = LinearRegression()
pipe = make_pipeline(column_trans,lr)
pipe.fit(x_train,y_train)
y_preds = pipe.predict(x_test)
r2_score(y_test,y_preds)

0.8457059008496111

In [ ]:
import pickle

In [ ]:
pickle.dump(pipe,open('LinearRegressionModel.pkl','wb'))

In [ ]:
pipe.predict(pd.DataFrame([['Maruti Suzuki Swift','Maruti',2019,100,'Petrol']],columns=['name','company','year','kms_driven','fuel_type']))

array([458894.11060714])

In [ ]:
#car['name'].unique()